### PR TITLE
Fix ArgSpec attribute access

### LINKED ISSUE #392: Regression of SplitEditorAreaPane in 6.1.0
The `SplitEditorAreaPane` regressed somewhere between the release of 6.0.0 and 6.1.0, and opening a new pane to have tabs side by side is now breaking with the error of the form:
```
Traceback (most recent call last):
  File "/Users/jrocher/.edm/envs/**/lib/python2.7/site-packages/pyface/ui/qt4/action/action_item.py", line 198, in _qt4_on_triggered
    if len(argspec.argspecargs) == 1:
AttributeError: 'ArgSpec' object has no attribute 'argspecargs'
```
Issue seen on Python 2.7 with both pyside and pyqt, and both on Windows and OSX.

### PR DESCRIPTION
**Pull request by rahulporuri**
The `ArgSpec` returned by `getargspec` does not contain an `argspecargs` attribute. This was introduced in the PR #370 .

See https://docs.python.org/3.6/library/inspect.html#inspect.getargspec for more information on the namedtuple returned by `getargspec`

fixes #392

### CODE REVIEW

**Comment by jonathanrocher** [comment]
Looks good to me.
